name: Build Hippo!

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  # Build the whole project (Rust WASM + React) using make
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Rust stable toolchain with WASM target
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      # This action tries to download a pre-build binary for wasm-pack
      # It's insecure to run binaries from an untrusted third party
      # but I like fast build and using a pre-built binary remove
      # more than 5 minutes from the pipeline run time
      - name: Install wasm-pack
        uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
          version: latest
          use-tool-cache: true

      - name: Build Rust WASM module, install NPM deps & generate React production build
        run: make build

      - name: Publish to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=react/build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

